compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  unplugin-vue-router@*:
    dependencies:
      "@vue/compiler-sfc": "*"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
